### ISSUE TITLE
about signed total Sobol index and first-order Sobol index

### ISSUE THREAD

**Issue by abcde-1447** [fel-thomas/Sobol-Attribution-Method#3]
Hi, it's me again.  I have been using your method for interpreting a few of my models, so far it works great!  

I noticed that you mentioned signed total Sobol index and first-order Sobol index, I am just wondering whether they are implemented somewhere in the code?

Thanks!

**Comment by fel-thomas** [comment]
Hi,   ;)
Thanks !!! The First-order indices are not implemented here to encourage the use of total indices (the first order indices get much less interesting results). Concerning the signed estimator, you just need to multiply the total order indices with the results of the Occlusion method (take the Sign(.) of the results) -- available with the Xplique library [Occlusion documentation](https://deel-ai.github.io/xplique/api/occlusion.html). 

e.g : Sti_delta(x) = Sign(Occlusion(x)) * Sti(x)

Nevertheless we have ideas to make the signed estimator more intelligent and a more elegant solution should come when we merge the Sobol method into the Xplique library.

**Comment by abcde-1447** [comment]
@fel-thomas Got it, thanks for the explanation!
